--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PocketmineSmashPE/KFA
branches:
- master
icon: https://github.com/PocketmineSmashPE/KFA/blob/master/logo.png
projects:
  KFA:
    path: "KFA/"
...
